### ISSUE TITLE
Remove html tags from a string

### ISSUE THREAD

**Issue by mtilda** [mxkay/techtrans-bot#29]
In order to send users the title of an invention, we will need to write a function that removes the html tags from the title.

Example string:
```
"Aircraft <span class=\"highlight\">Engine</span> Icing Event Avoidance and Mitigation"
```

Output:
```
"Aircraft Engine Icing Event Avoidance and Mitigation"
```

**Comment by rajkumarGosavi** [comment]
Hi,
I am interested to work on this issue.
