### ISSUE TITLE
Reorganize and refactor

### ISSUE THREAD

**Issue by mtilda** [mxkay/techtrans-bot#33]
Reorganize and refactoring the code to match this new design.

![20210516_214658.jpg](https://user-images.githubusercontent.com/63630918/118421973-3e32e200-b690-11eb-81ff-23b63e6a610c.jpg)

Each section on the whiteboard corresponds to a file.
- `bot.go`
    -   Dispatch `irc` to send and receive messages at a specified (`Target`) IRC server
    -   Decide how to respond to incoming messages
- `irc.go`
    -   Manage connection to IRC server
    -   Listen to IRC server
    -   Read incoming IRC lines
    -   Write lines to IRC server
    -   Send messages
    -   Invoke `bot.Chat()` when a message is received (in `HandleLine`)*
    -   Play PING PONG (avoid premature disconnections)
- `tech.go`
    -   Fetch and package data from TechTransfer API for use in response to `!tech` command

`cli.go` is not depicted in this diagram, but it should remain more or less the same (other issues will detail improvements).

* `bot.Chat()` may be a go routine, so `irc` continues reading lines even if `FetchTech()` or some other process in `bot.Chat()` takes a long time.

**Comment by mxkay** [comment]
Correction: `Listen()` should receive `OAuthCred` as well as `Targets`. Both of these structures should be accessible in `irc.go` as well as `bot.go`; however only `Bot` stores these in a field.

**Comment by mtilda** [comment]
Nah, make it look like this instead!

![20210517_065410.jpg](https://user-images.githubusercontent.com/63630918/118477517-c17a2500-b6dc-11eb-8496-a1d56106101d.jpg)
